name: QEMU tests

on: [ workflow_dispatch ]

jobs:
  version-test:
    name: version-push tests
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check qemu version
      run: |
        dpkg -l | grep qemu

