name: QEMU tests

on: [ workflow_dispatch ]

jobs:
  version-test:
    name: version-push tests
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check qemu version
      run: |
        ls -la /proc/sys/fs/binfmt_misc/
        dpkg -l

    - name: Build base image
      uses: home-assistant/builder@2024.08.2
      with:
        args: |
          $BUILD_ARGS \
          --aarch64 \
          --target /data/alpine \
          --base 3.20
    - name: Check qemu version
      run: |
        ls -la /proc/sys/fs/binfmt_misc/
        qemu-aarch64-static --version
