name: Version tests

on: [ workflow_dispatch ]

jobs:
  version-test:
    name: version-push tests
    runs-on: ubuntu-20.04

    steps:

    - name: Initialize git
      uses: home-assistant/actions/helpers/git-init@master
      with:
        name: ${{ secrets.GIT_NAME }}
        email: ${{ secrets.GIT_EMAIL }}
        token: ${{ secrets.GIT_TOKEN }}

    - name: Test Version bump supervisor
      uses: agners/actions/helpers/version-push@test
      with:
        key: "supervisor"
        version: "2020.12"
        channel: "dev"

    - name: Test Version bump hassos
      uses: agners/actions/helpers/version-push@test
      with:
        key: "hassos[]"
        version: "5.10"
        channel: "dev"

    - name: Test Version bump hassos ova only
      uses: agners/actions/helpers/version-push@test
      with:
        key: "hassos.ova"
        version: "5.11"
        channel: "dev"
